# -*- coding: utf-8 -*-
"""Glass vs. Plastic Items.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJHAAHCk0IZZtva-glz77I-ojj8go7Z0

# Glass_vs_Plastic_Items_Classification

**Student ID:** 22F23626  
**Student Name:** Shahla Suliman Alaamri  
**Module:** Artificial Intelligence and Deep Learning  
**Assignment:** Binary Image Classification using Deep Learning  
**Platform:** Google Colab  
**Dataset/Topic:** Glass vs Plastic Items - Kaggle

## Project Description

This project focuses on a binary image classification problem using deep learning. The selected topic is Glass vs Plastic Items classification. The main objective is to train a model that can classify whether an item in an image belongs to the Glass class or the Plastic class.

The project will be implemented using Python in Google Colab. A Convolutional Neural Network model will be built from scratch, and a pre-trained deep learning model will also be used for comparison. The performance of both models will be evaluated using classification metrics such as accuracy, precision, recall, and F1-score.
"""

!pip install kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle kernels pull supermarkethobo/glass-vs-plastic-items-image-classification

import os

print(os.listdir())

import os

for file in os.listdir():
    print(file)

# Search inside the downloaded notebook for possible dataset names or paths
import json

notebook_path = "glass-vs-plastic-items-image-classification.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

keywords = ["dataset", "glass", "plastic", "/kaggle/input", "train", "test", "ImageDataGenerator", "flow_from_directory"]

for cell in notebook["cells"]:
    source = "".join(cell.get("source", []))
    for keyword in keywords:
        if keyword.lower() in source.lower():
            print(source)
            print("-" * 100)
            break

# Install fastbook to download images from DuckDuckGo
!pip install fastbook

# Import required libraries
from fastbook import *
from fastai.vision.all import *
import os
from pathlib import Path

# Create dataset folders
path = Path("glass_plastic_dataset")

glass_path = path / "glass"
plastic_path = path / "plastic"

glass_path.mkdir(parents=True, exist_ok=True)
plastic_path.mkdir(parents=True, exist_ok=True)

print("Dataset folders created successfully.")

# Extract hard-coded image URLs from the downloaded Kaggle notebook
import json
import re
import ast

notebook_path = "glass-vs-plastic-items-image-classification.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

all_code = "\n".join(
    "".join(cell.get("source", []))
    for cell in notebook["cells"]
    if cell.get("cell_type") == "code"
)

def extract_url_list(variable_name):
    pattern = rf"{variable_name}\s*=\s*(\[.*?\])"
    match = re.search(pattern, all_code, re.DOTALL)
    if match:
        return ast.literal_eval(match.group(1))
    return []

glass_urls = extract_url_list("glass_urls")
plastic_urls = extract_url_list("plastic_urls")

print("Glass URLs found:", len(glass_urls))
print("Plastic URLs found:", len(plastic_urls))

# Create dataset folders
import os
from pathlib import Path

path = Path("glass_plastic_dataset")
glass_path = path / "glass"
plastic_path = path / "plastic"

glass_path.mkdir(parents=True, exist_ok=True)
plastic_path.mkdir(parents=True, exist_ok=True)

print("Folders created successfully.")

# Download images safely with timeout
import requests
from PIL import Image
from io import BytesIO

def safe_download_images(urls, folder, limit=40):
    count = 0

    for i, url in enumerate(urls[:limit]):
        try:
            response = requests.get(url, timeout=8)

            if response.status_code == 200:
                img = Image.open(BytesIO(response.content)).convert("RGB")
                img.save(folder / f"image_{i}.jpg")
                count += 1

        except Exception:
            pass

    return count

glass_count = safe_download_images(glass_urls, glass_path, limit=40)
plastic_count = safe_download_images(plastic_urls, plastic_path, limit=40)

print("Glass images downloaded:", glass_count)
print("Plastic images downloaded:", plastic_count)

# Download more images from later URLs to increase dataset size
def safe_download_more_images(urls, folder, start=40, end=120, prefix="more"):
    count = 0

    for i, url in enumerate(urls[start:end]):
        try:
            response = requests.get(url, timeout=8)

            if response.status_code == 200:
                img = Image.open(BytesIO(response.content)).convert("RGB")
                img.save(folder / f"{prefix}_{start+i}.jpg")
                count += 1

        except Exception:
            pass

    return count

more_glass_count = safe_download_more_images(glass_urls, glass_path, start=40, end=120, prefix="glass")
more_plastic_count = safe_download_more_images(plastic_urls, plastic_path, start=40, end=120, prefix="plastic")

print("More glass images downloaded:", more_glass_count)
print("More plastic images downloaded:", more_plastic_count)

# Check updated final number of images
glass_count = len(list(glass_path.glob("*")))
plastic_count = len(list(plastic_path.glob("*")))

print("Number of glass images:", glass_count)
print("Number of plastic images:", plastic_count)
print("Total images:", glass_count + plastic_count)

# Display sample images from the dataset
import matplotlib.pyplot as plt
from PIL import Image
import random

image_files = list(path.glob("*/*"))
sample_images = random.sample(image_files, 6)

plt.figure(figsize=(12, 6))

for i, img_path in enumerate(sample_images, 1):
    img = Image.open(img_path)

    plt.subplot(2, 3, i)
    plt.imshow(img)
    plt.axis("off")
    plt.title(img_path.parent.name)

plt.tight_layout()
plt.show()

# Import ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Image settings
IMG_SIZE = 224
BATCH_SIZE = 16

# Training generator with augmentation
train_generator = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=15,
    zoom_range=0.1,
    horizontal_flip=True
)

# Validation generator without augmentation
val_generator = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

# Load training images
train_images = train_generator.flow_from_directory(
    path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    subset="training",
    shuffle=True
)

# Load validation images
val_images = val_generator.flow_from_directory(
    path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    subset="validation",
    shuffle=False
)

# Check class indices
print("Class indices:")
print(train_images.class_indices)

# Import TensorFlow and Keras layers
import tensorflow as tf
from tensorflow.keras import layers, models

# Build CNN model from scratch
cnn_model = models.Sequential([
    layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3)),

    # First convolution block
    layers.Conv2D(32, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    # Second convolution block
    layers.Conv2D(64, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    # Third convolution block
    layers.Conv2D(128, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    # Convert feature maps into one vector
    layers.Flatten(),

    # Fully connected layer
    layers.Dense(128, activation="relu"),

    # Dropout to reduce overfitting
    layers.Dropout(0.5),

    # Output layer for binary classification
    layers.Dense(1, activation="sigmoid")
])

# Show model architecture
cnn_model.summary()

# Compile CNN model
cnn_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Train CNN model
history_cnn = cnn_model.fit(
    train_images,
    validation_data=val_images,
    epochs=10
)

# Evaluate CNN model on validation data
cnn_loss, cnn_accuracy = cnn_model.evaluate(val_images)

print("CNN Validation Loss:", cnn_loss)
print("CNN Validation Accuracy:", cnn_accuracy)

# Plot CNN training and validation accuracy
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.plot(history_cnn.history["accuracy"], label="Training Accuracy")
plt.plot(history_cnn.history["val_accuracy"], label="Validation Accuracy")
plt.title("CNN Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

# Plot CNN training and validation loss
plt.figure(figsize=(8, 5))
plt.plot(history_cnn.history["loss"], label="Training Loss")
plt.plot(history_cnn.history["val_loss"], label="Validation Loss")
plt.title("CNN Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

# Build a smaller CNN model to reduce overfitting
cnn_model = models.Sequential([
    layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3)),

    layers.Conv2D(16, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(32, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.GlobalAveragePooling2D(),

    layers.Dense(64, activation="relu"),
    layers.Dropout(0.5),

    layers.Dense(1, activation="sigmoid")
])

cnn_model.summary()

cnn_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history_cnn = cnn_model.fit(
    train_images,
    validation_data=val_images,
    epochs=15
)

cnn_loss, cnn_accuracy = cnn_model.evaluate(val_images)

print("CNN Validation Loss:", cnn_loss)
print("CNN Validation Accuracy:", cnn_accuracy)

# Import MobileNetV2 pre-trained model
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Data generators for MobileNetV2
mobilenet_train_generator = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

mobilenet_val_generator = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2
)

# Load MobileNetV2 training images
mobilenet_train_images = mobilenet_train_generator.flow_from_directory(
    path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    subset="training",
    shuffle=True
)

# Load MobileNetV2 validation images
mobilenet_val_images = mobilenet_val_generator.flow_from_directory(
    path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    subset="validation",
    shuffle=False
)

print("Class indices:")
print(mobilenet_train_images.class_indices)

# Load MobileNetV2 base model
base_model = MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights="imagenet"
)

# Freeze base model layers
base_model.trainable = False

# Build transfer learning model
mobilenet_model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.BatchNormalization(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(1, activation="sigmoid")
])

mobilenet_model.summary()

# Compile MobileNetV2 model
mobilenet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Callbacks to improve training
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.2,
    patience=3,
    min_lr=0.000001
)

# Train MobileNetV2 model
history_mobilenet = mobilenet_model.fit(
    mobilenet_train_images,
    validation_data=mobilenet_val_images,
    epochs=20,
    callbacks=[early_stopping, reduce_lr]
)

# Evaluate MobileNetV2 model
mobilenet_loss, mobilenet_accuracy = mobilenet_model.evaluate(mobilenet_val_images)

print("MobileNetV2 Validation Loss:", mobilenet_loss)
print("MobileNetV2 Validation Accuracy:", mobilenet_accuracy)

# Fine-tune the last layers of MobileNetV2
base_model.trainable = True

# Freeze most layers and train only the last 30 layers
for layer in base_model.layers[:-30]:
    layer.trainable = False

# Recompile with a very small learning rate
mobilenet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Continue training with fine-tuning
history_finetune = mobilenet_model.fit(
    mobilenet_train_images,
    validation_data=mobilenet_val_images,
    epochs=10,
    callbacks=[early_stopping, reduce_lr]
)

# Evaluate fine-tuned MobileNetV2 model
finetuned_loss, finetuned_accuracy = mobilenet_model.evaluate(mobilenet_val_images)

print("Fine-tuned MobileNetV2 Validation Loss:", finetuned_loss)
print("Fine-tuned MobileNetV2 Validation Accuracy:", finetuned_accuracy)

# Create comparison table
import pandas as pd

comparison_df = pd.DataFrame({
    "Model": [
        "CNN from Scratch",
        "MobileNetV2",
        "Fine-tuned MobileNetV2"
    ],
    "Validation Loss": [
        cnn_loss,
        mobilenet_loss,
        finetuned_loss
    ],
    "Validation Accuracy": [
        cnn_accuracy,
        mobilenet_accuracy,
        finetuned_accuracy
    ]
})

display(comparison_df)

# Classification report for Fine-tuned MobileNetV2
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

mobilenet_val_images.reset()

predictions = mobilenet_model.predict(mobilenet_val_images)
predicted_classes = (predictions > 0.5).astype("int32").flatten()

true_classes = mobilenet_val_images.classes
class_names = list(mobilenet_val_images.class_indices.keys())

print("Fine-tuned MobileNetV2 Classification Report:")
print(classification_report(true_classes, predicted_classes, target_names=class_names))

# Confusion matrix for Fine-tuned MobileNetV2
cm = confusion_matrix(true_classes, predicted_classes)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=class_names
)

disp.plot()
plt.title("Fine-tuned MobileNetV2 Confusion Matrix")
plt.show()

# Final results summary
print("Final Model Comparison")
print("----------------------")
print("CNN Validation Accuracy:", round(cnn_accuracy, 4))
print("MobileNetV2 Validation Accuracy:", round(mobilenet_accuracy, 4))
print("Fine-tuned MobileNetV2 Validation Accuracy:", round(finetuned_accuracy, 4))

print("\nBest Model: Fine-tuned MobileNetV2")

# Save the best model
mobilenet_model.save("best_glass_plastic_mobilenet_model.keras")

print("Best Fine-tuned MobileNetV2 model saved successfully.")